# Generated by Django 2.1.7 on 2020-12-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Quiz Answer')),
                ('created_date', models.DateTimeField(verbose_name='Answer Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Quiz Question')),
                ('created_date', models.DateTimeField(verbose_name='Question Created Date')),
            ],
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizusers.QuizQuestions'),
        ),
    ]
